---
platform: linux
image: docker:///sedouard/azure-cpi-release
inputs:
  - name: bosh-cpi-release
run:
  path: bosh-cpi-release/ci/tasks/azure-provision.sh
params:
    AZURE_USER_NAME: replace-me
    AZURE_USER_PASSWORD: replace-me
    AZURE_REGION_NAME: replace-me
    AZURE_GROUP_NAME: replace-me