---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: bosh-cpi-src

outputs:
  - name: cpi-release

run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
