---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: pipelines
  - name: environment
  - name: bats
  - name: director-state
  - name: stemcell
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/run-az-bats.sh

params:
  INFRASTRUCTURE:                                    ""
  STEMCELL_NAME:                                     ""
  BAT_INFRASTRUCTURE:                                ""
  BAT_RSPEC_FLAGS:                                   ""
  AZURE_BATS_ZONE:                                   ""
