director_uuid: REPLACE_WITH_YOUR_DIRECTOR_UUID

meta:
  # Used as a prefix for the deployment name
  #
  # e.g. `environment: cf-tabasco` makes a deployment named cf-tabasco-mysql
  environment: REPLACE_WITH_YOUR_ENVIRONMENT_NAME

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
networks:
- name: mysql1
  type: manual
  subnets:
  - range: 10.0.32.0/24
    reserved:
      - 10.0.32.2 - 10.0.32.3
    static:
      - 10.0.32.4 - 10.0.32.8
    gateway: 10.0.32.1
    dns:
      - 10.0.0.100
    cloud_properties:
      virtual_network_name: (( properties.template_only.azure.virtual_network_name ))
      subnet_name: (( properties.template_only.azure.subnet_names.mysql1 ))
- name: mysql2
  type: manual
  subnets:
  - range: 10.0.33.0/24
    reserved:
      - 10.0.33.2 - 10.0.33.3
    static:
      - 10.0.33.4 - 10.0.33.8
    gateway: 10.0.33.1
    dns:
      - 10.0.0.100
    cloud_properties:
      virtual_network_name: (( properties.template_only.azure.virtual_network_name ))
      subnet_name: (( properties.template_only.azure.subnet_names.mysql2 ))
- name: mysql3
  type: manual
  subnets:
  - range: 10.0.34.0/24
    reserved:
      - 10.0.34.2 - 10.0.34.3
    static:
      - 10.0.34.4 - 10.0.34.8
    gateway: 10.0.34.1
    dns:
      - 10.0.0.100
    cloud_properties:
      virtual_network_name: (( properties.template_only.azure.virtual_network_name ))
      subnet_name: (( properties.template_only.azure.subnet_names.mysql3 ))
- name: compilation
  type: manual
  subnets:
  - range: 10.0.35.0/24
    name: default_unused
    reserved:
      - 10.0.35.2 - 10.0.35.3
    static:
      - 10.0.35.4 - 10.0.35.8
    gateway: 10.0.35.1
    dns:
      - 10.0.0.100
    cloud_properties:
      virtual_network_name: (( properties.template_only.azure.virtual_network_name ))
      subnet_name: (( properties.template_only.azure.subnet_names.compilation ))

properties:
  cf:
    # these come from your cf-release manifest
    admin_username: REPLACE_WITH_YOUR_CF_ADMIN_USERNAME
    admin_password: REPLACE_WITH_YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: REPLACE_WITH_TRUE_OR_FALSE # True if you don't have a trusted SSL certificate, false if you do

  domain: REPLACE_WITH_YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-msyql.external_domain.
  app_domains:
  - REPLACE_WITH_YOUR_CF_APPS_DOMAIN
  nats:
    user: nats
    password: REPLACE_WITH_NATS_PASSWORD_FROM_CF_RELEASE
    machines:
      - REPLACE_WITH_NATS_IP_ADDRESS_FROM_CF_RELEASE
    port: 4222

  template_only:
    azure:
      virtual_network_name: REPLACE_WITH_YOUR_VIRTUAL_NETWORK_NAME
      subnet_names:
        mysql1: REPLACE_WITH_YOUR_SUBNET_NAME_1
        mysql2: REPLACE_WITH_YOUR_SUBNET_NAME_2
        mysql3: REPLACE_WITH_YOUR_SUBNET_NAME_3
        compilation: REPLACE_WITH_YOUR_COMPILATION_SUBNET


jobs:
# Jobs for cf-mysql-release are below
- name: mysql_z1
  properties:
    admin_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process
    bootstrap_endpoint:
      username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP
      password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP

- name: cf-mysql-broker_z1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP # eg. cc
    auth_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    cookie_secret: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    services:
      - name: p-mysql
        dashboard_client:
          secret: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
        plans:
        - name: 100mb
          id: ab08f1bc-e6fc-4b56-a767-ee0fea6e3f20
          description: Shared MySQL Server
          max_storage_mb: 100
          max_user_connections: 20
          metadata:
            costs:
            - amount:
                usd: 0.0
              unit: MONTH
            bullets:
              - Shared MySQL server
              - 100 MB storage
              - 20 concurrent connections
            displayName: "100 MB"
        - name: 1gb
          id: 11d0aa36-dcec-4021-85f5-ea4d9a5c8342
          description: Shared MySQL Server
          max_storage_mb: 1000
          max_user_connections: 40
          metadata:
            costs:
            - amount:
                usd: 0.0
              unit: MONTH
            bullets:
              - Shared MySQL server
              - 1000 MB storage
              - 40 concurrent connections
            displayName: "1 GB"

- name: proxy_z1
  release: cf-mysql
  properties:
    proxy:
      api_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP
      api_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
